# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_one/uploads/%Y/%m/%d/')),
            ],
        ),
    ]
