# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_imports', '0006_auto_20180526_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='filename',
        ),
    ]
